# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"

    working_directory: /go/src/github.com/sbracaloni/thread-safe-action
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get golang.org/x/lint/golint && golint -set_exit_status ./action/
      - run: test -z $(gofmt -l ./action)
      - run: go test -v ./action
